const data = {
  products: [
    {
      _id: '1',
      name: 'Adidas Black Canvas',
      slug: 'adidas-black-canvas',
      category: 'shirts',
      image: '/pictures/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Very good quality shoes pure black color',
    },
    {
      _id: '2',
      name: 'Adidas White Sneakers',
      slug: 'adidas-white-sneakers',
      category: 'Shirts',
      image: '/pictures/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Air Jordan',
      slug: 'nike-air-jordan',
      category: 'Pants',
      image: '/pictures/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description:
        'Very high quality sports shoes newly launched by Nike Air Jordan ',
    },
    {
      _id: '4',
      name: 'Nike White Shoes',
      slug: 'nike-white-shoes',
      category: 'Pants',
      image: '/pictures/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'White color shoes with soft sole',
    },
    {
      _id: '5',
      name: 'Nike Air',
      slug: 'nike-air',
      category: 'Pants',
      image: '/pictures/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'New category shoed from Nike Air available at cheap price',
    },
    {
      _id: '6',
      name: 'Nike Clothed',
      slug: 'nike-clothed',
      category: 'Pants',
      image: '/pictures/p6.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Outstanding quality shoes available in cloth material',
    },
  ],
};

export default data;
